version: '3.7'

services:
  # app:
  #   container_name: GatewayManagementApi
  #   build: 
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #     - 3000:3000
  #   volumes:
  #     - .:/usr/app
  #     - /usr/app/node_modules
  #   command: node src/index.js 
  #   env_file:
  #     - .env
  #   depends_on:
  #     - mongo
  mongo:
    image: mongo:latest
    ports:
      - 27018:27017
    volumes:
      - mongodb_data_container:/data/db

volumes:
  mongodb_data_container: